# Generated by Django 6.0 on 2025-12-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography'),
        ),
        migrations.AddField(
            model_name='author',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload CV (PDF recommended)', null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='author',
            name='degree',
            field=models.CharField(blank=True, help_text='Highest degree (e.g., PhD in Computer Science)', max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='author',
            name='google_scholar',
            field=models.URLField(blank=True, help_text='Google Scholar profile URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='orcid',
            field=models.CharField(blank=True, help_text='ORCID ID', max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/authors/'),
        ),
        migrations.AddField(
            model_name='author',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Research areas and interests'),
        ),
        migrations.AddField(
            model_name='author',
            name='researchgate',
            field=models.URLField(blank=True, help_text='ResearchGate profile URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, help_text='Personal/academic website'),
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, help_text='About the institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year established', null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('university', 'University'), ('research_institute', 'Research Institute'), ('government', 'Government Organization'), ('private', 'Private Research Organization'), ('industry', 'Industry/Corporate R&D'), ('hospital', 'Hospital/Medical Center'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/institutions/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='research_areas',
            field=models.TextField(blank=True, help_text='Main research areas'),
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='total_researchers',
            field=models.PositiveIntegerField(blank=True, help_text='Number of researchers', null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
