# Generated by Django 5.2.8 on 2026-01-05 05:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_author_bio_author_cv_author_degree_author_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_index', models.IntegerField(default=0, help_text='h-index: h papers with at least h citations each', validators=[django.core.validators.MinValueValidator(0)])),
                ('i10_index', models.IntegerField(default=0, help_text='i10-index: number of publications with at least 10 citations', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_citations', models.IntegerField(default=0, help_text='Total number of citations across all publications', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_reads', models.IntegerField(default=0, help_text='Total number of times publications were read', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_downloads', models.IntegerField(default=0, help_text='Total number of PDF downloads', validators=[django.core.validators.MinValueValidator(0)])),
                ('recommendations_count', models.IntegerField(default=0, help_text='Total recommendations received', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_publications', models.IntegerField(default=0, help_text='Total number of published works', validators=[django.core.validators.MinValueValidator(0)])),
                ('average_citations_per_paper', models.DecimalField(decimal_places=2, default=0.0, help_text='Average citations per publication', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.author')),
            ],
            options={
                'verbose_name': 'Author Statistics',
                'verbose_name_plural': 'Author Statistics',
            },
        ),
    ]
