# Generated by Django 5.2.8 on 2026-01-12 06:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authorstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_publications', models.IntegerField(default=0, help_text='Total number of published works from this institution', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_citations', models.IntegerField(default=0, help_text='Total citations across all publications', validators=[django.core.validators.MinValueValidator(0)])),
                ('average_citations_per_paper', models.DecimalField(decimal_places=2, default=0.0, help_text='Average citations per publication', max_digits=10)),
                ('total_reads', models.IntegerField(default=0, help_text='Total number of times publications were read', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_downloads', models.IntegerField(default=0, help_text='Total number of PDF downloads', validators=[django.core.validators.MinValueValidator(0)])),
                ('recommendations_count', models.IntegerField(default=0, help_text='Total recommendations received', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_authors', models.IntegerField(default=0, help_text='Total number of unique authors from this institution', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.institution')),
            ],
            options={
                'verbose_name': 'Institution Statistics',
                'verbose_name_plural': 'Institution Statistics',
            },
        ),
    ]
