# Generated by Django 5.2.8 on 2026-01-12 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_institutionstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0, help_text='Total number of registered users', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_authors', models.IntegerField(default=0, help_text='Total number of authors', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_institutions', models.IntegerField(default=0, help_text='Total number of institutions', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_publications', models.IntegerField(default=0, help_text='Total publications in the system', validators=[django.core.validators.MinValueValidator(0)])),
                ('published_count', models.IntegerField(default=0, help_text='Number of published works', validators=[django.core.validators.MinValueValidator(0)])),
                ('draft_count', models.IntegerField(default=0, help_text='Number of draft publications', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_citations', models.IntegerField(default=0, help_text='Total citations across all publications', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_reads', models.IntegerField(default=0, help_text='Total reads across all publications', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_downloads', models.IntegerField(default=0, help_text='Total downloads across all publications', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_journals', models.IntegerField(default=0, help_text='Total number of journals', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_topics', models.IntegerField(default=0, help_text='Total number of topics', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Statistics',
                'verbose_name_plural': 'Admin Statistics',
            },
        ),
    ]
