# Generated by Django 5.2.7 on 2026-02-03 06:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sponsor/Partner name', max_length=200)),
                ('logo', models.ImageField(help_text='Logo image', upload_to='sponsors/')),
                ('website_url', models.URLField(blank=True, help_text='Sponsor website URL', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('show_on_author_supporter', models.BooleanField(default=False, help_text='Show on Author Supporter page')),
                ('show_on_institutional_supporter', models.BooleanField(default=False, help_text='Show on Institutional Supporter page')),
                ('show_on_sponsorship_partnership', models.BooleanField(default=False, help_text='Show on Sponsorship & Partnership page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor/Partner',
                'verbose_name_plural': 'Sponsors/Partners',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPartnershipContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_intro', models.TextField(help_text='Sponsorship model introduction (rich text JSON)')),
                ('partnership_intro', models.TextField(help_text='Partnership model introduction (rich text JSON)')),
                ('join_cta', models.TextField(help_text='Join as sponsor/partner call-to-action (rich text JSON)')),
            ],
            options={
                'verbose_name': 'Sponsorship/Partnership Content',
                'verbose_name_plural': 'Sponsorship/Partnership Content',
            },
        ),
        migrations.CreateModel(
            name='SupportPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('author_supporter', 'Author Supporter Model'), ('institutional_supporter', 'Institutional Supporter Model'), ('sponsorship_partnership', 'Sponsorship & Partnership')], help_text='Type of support page', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Page title', max_length=200)),
                ('overview', models.TextField(help_text='Overview section content (rich text JSON)', validators=[django.core.validators.MinLengthValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Page',
                'verbose_name_plural': 'Support Pages',
                'ordering': ['page_type'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Partnership point text')),
                ('order', models.IntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_points', to='support.sponsorshippartnershipcontent')),
            ],
            options={
                'verbose_name': 'Partnership Point',
                'verbose_name_plural': 'Partnership Points',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Sponsorship point text')),
                ('order', models.IntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_points', to='support.sponsorshippartnershipcontent')),
            ],
            options={
                'verbose_name': 'Sponsorship Point',
                'verbose_name_plural': 'Sponsorship Points',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SupportBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Benefit title', max_length=200)),
                ('description', models.TextField(help_text='Benefit description (rich text JSON or plain text)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('support_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='support.supportpage')),
            ],
            options={
                'verbose_name': 'Support Benefit',
                'verbose_name_plural': 'Support Benefits',
                'ordering': ['support_page', 'order'],
            },
        ),
        migrations.AddField(
            model_name='sponsorshippartnershipcontent',
            name='support_page',
            field=models.OneToOneField(limit_choices_to={'page_type': 'sponsorship_partnership'}, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_content', to='support.supportpage'),
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text="Pricing category (e.g., 'Senior Researcher / Professor')", max_length=200)),
                ('npr_amount', models.DecimalField(decimal_places=2, help_text='Amount in Nepali Rupees', max_digits=10)),
                ('usd_amount', models.DecimalField(decimal_places=2, help_text='Amount in US Dollars', max_digits=10)),
                ('purpose', models.TextField(help_text='Purpose of this pricing tier')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('support_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='support.supportpage')),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'ordering': ['support_page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WhySupportPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Point title', max_length=200)),
                ('description', models.TextField(help_text='Point description (rich text JSON)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('support_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_support_points', to='support.supportpage')),
            ],
            options={
                'verbose_name': 'Why Support Point',
                'verbose_name_plural': 'Why Support Points',
                'ordering': ['support_page', 'order'],
            },
        ),
    ]
