# Generated by Django 6.0 on 2026-02-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorshippartnershipcontent',
            name='support_page',
        ),
        migrations.RemoveField(
            model_name='sponsorshippoint',
            name='content',
        ),
        migrations.AddField(
            model_name='supportpage',
            name='partnership_detail',
            field=models.TextField(blank=True, help_text='Partnership details and benefits (rich text/HTML)'),
        ),
        migrations.AddField(
            model_name='supportpage',
            name='sponsorship_detail',
            field=models.TextField(blank=True, help_text='Sponsorship details and benefits (rich text/HTML)'),
        ),
        migrations.DeleteModel(
            name='PartnershipPoint',
        ),
        migrations.DeleteModel(
            name='SponsorshipPartnershipContent',
        ),
        migrations.DeleteModel(
            name='SponsorshipPoint',
        ),
    ]
