# Generated by Django 5.2.8 on 2025-12-30 09:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_author_bio_author_cv_author_degree_author_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True, help_text='Publication abstract')),
                ('publication_type', models.CharField(choices=[('journal_article', 'Journal Article'), ('conference_paper', 'Conference Paper'), ('book_chapter', 'Book Chapter'), ('preprint', 'Preprint'), ('thesis', 'Thesis/Dissertation'), ('technical_report', 'Technical Report'), ('poster', 'Poster'), ('presentation', 'Presentation'), ('book', 'Book'), ('review', 'Review Article'), ('other', 'Other')], default='journal_article', max_length=30)),
                ('pdf_file', models.FileField(blank=True, help_text='Upload PDF of the publication', null=True, upload_to='publications/pdfs/')),
                ('doi', models.CharField(blank=True, db_index=True, help_text='Digital Object Identifier', max_length=255)),
                ('published_date', models.DateField(blank=True, help_text='Publication date', null=True)),
                ('journal_name', models.CharField(blank=True, help_text='Journal or conference name', max_length=300)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, help_text='e.g., 123-145', max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('co_authors', models.TextField(blank=True, help_text='Comma-separated list of co-authors')),
                ('pubmed_id', models.CharField(blank=True, help_text='PubMed ID', max_length=50)),
                ('arxiv_id', models.CharField(blank=True, help_text='arXiv ID', max_length=50)),
                ('pubmed_central_id', models.CharField(blank=True, help_text='PMC ID', max_length=50)),
                ('is_published', models.BooleanField(default=True, help_text='Whether the publication is publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='users.author')),
                ('erratum_from', models.ForeignKey(blank=True, help_text='Original publication if this is an erratum', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errata', to='publications.publication')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeSHTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='MeSH term', max_length=255)),
                ('term_type', models.CharField(choices=[('major', 'Major Topic'), ('minor', 'Minor Topic')], default='minor', max_length=50)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesh_terms', to='publications.publication')),
            ],
        ),
        migrations.CreateModel(
            name='LinkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('pubmed', 'PubMed'), ('pmc', 'PubMed Central'), ('google_scholar', 'Google Scholar'), ('doi', 'DOI Link'), ('arxiv', 'arXiv'), ('researchgate', 'ResearchGate'), ('academia', 'Academia.edu'), ('publisher', 'Publisher Website'), ('preprint', 'Preprint Server'), ('dataset', 'Dataset'), ('code', 'Source Code'), ('other', 'Other')], max_length=30)),
                ('url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_outs', to='publications.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citing_title', models.CharField(help_text='Title of the work citing this publication', max_length=500)),
                ('citing_authors', models.TextField(help_text='Authors of the citing work')),
                ('citing_doi', models.CharField(blank=True, help_text='DOI of citing work', max_length=255)),
                ('citing_year', models.PositiveIntegerField(blank=True, help_text='Year of citation', null=True)),
                ('citing_journal', models.CharField(blank=True, help_text='Journal/source of citing work', max_length=300)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='publications.publication')),
            ],
            options={
                'ordering': ['-citing_year', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_email', models.EmailField(blank=True, help_text='Email of reader if logged in', max_length=254)),
                ('reader_ip', models.GenericIPAddressField(blank=True, help_text='IP address of reader', null=True)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_events', to='publications.publication')),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citations_count', models.PositiveIntegerField(default=0, help_text='Number of citations')),
                ('reads_count', models.PositiveIntegerField(default=0, help_text='Number of reads')),
                ('downloads_count', models.PositiveIntegerField(default=0, help_text='Number of downloads')),
                ('recommendations_count', models.PositiveIntegerField(default=0, help_text='Number of recommendations')),
                ('altmetric_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Altmetric attention score', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('field_citation_ratio', models.DecimalField(decimal_places=2, default=0.0, help_text='Relative citation ratio', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='publications.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_text', models.TextField(help_text='Full reference text')),
                ('reference_title', models.CharField(blank=True, max_length=500)),
                ('reference_authors', models.TextField(blank=True)),
                ('reference_doi', models.CharField(blank=True, max_length=255)),
                ('reference_year', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_journal', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in reference list')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='publications.publication')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['author', '-published_date'], name='publication_author__df6e61_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['doi'], name='publication_doi_6c08dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meshterm',
            unique_together={('publication', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='linkout',
            unique_together={('publication', 'link_type', 'url')},
        ),
    ]
