# Generated by Django 5.2.8 on 2025-12-30 09:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('users', '0002_author_bio_author_cv_author_degree_author_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Journal title', max_length=300)),
                ('short_title', models.CharField(blank=True, help_text='Abbreviated title', max_length=100)),
                ('issn', models.CharField(blank=True, db_index=True, help_text='ISSN number', max_length=20)),
                ('e_issn', models.CharField(blank=True, help_text='Electronic ISSN', max_length=20)),
                ('description', models.TextField(help_text='About the journal')),
                ('scope', models.TextField(blank=True, help_text='Journal scope and aims')),
                ('cover_image', models.ImageField(blank=True, help_text='Journal cover image', null=True, upload_to='journals/covers/')),
                ('publisher_name', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('bimonthly', 'Bi-monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Bi-annual'), ('annual', 'Annual')], default='quarterly', max_length=20)),
                ('established_year', models.PositiveIntegerField(blank=True, help_text='Year established', null=True)),
                ('language', models.CharField(default='English', help_text='Primary language', max_length=100)),
                ('about_journal', models.TextField(blank=True, help_text='Detailed information about the journal')),
                ('ethics_policies', models.TextField(blank=True, help_text='Ethics and editorial policies')),
                ('writing_formatting', models.TextField(blank=True, help_text='Writing and formatting guidelines')),
                ('submitting_manuscript', models.TextField(blank=True, help_text='Manuscript submission guidelines')),
                ('help_support', models.TextField(blank=True, help_text='Help and support information')),
                ('contact_email', models.EmailField(blank=True, help_text='Journal contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('contact_address', models.TextField(blank=True, help_text='Contact address')),
                ('website', models.URLField(blank=True, help_text='Journal website')),
                ('doi_prefix', models.CharField(blank=True, help_text='DOI prefix for articles', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether journal is actively publishing')),
                ('is_open_access', models.BooleanField(default=False, help_text='Open access journal')),
                ('peer_reviewed', models.BooleanField(default=True, help_text='Peer-reviewed journal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='users.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(help_text='Volume number')),
                ('issue_number', models.PositiveIntegerField(help_text='Issue number')),
                ('title', models.CharField(blank=True, help_text='Special issue title (optional)', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Issue description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journals/issues/covers/')),
                ('publication_date', models.DateField(help_text='Publication date')),
                ('submission_deadline', models.DateField(blank=True, help_text='Submission deadline for this issue', null=True)),
                ('doi', models.CharField(blank=True, help_text='DOI for this issue', max_length=255)),
                ('pages_range', models.CharField(blank=True, help_text='e.g., 1-150', max_length=50)),
                ('editorial_note', models.TextField(blank=True, help_text="Editor's note for this issue")),
                ('guest_editors', models.TextField(blank=True, help_text='Guest editors (for special issues)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('current', 'Current Issue'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_special_issue', models.BooleanField(default=False, help_text='Is this a special issue?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='publications.journal')),
            ],
            options={
                'ordering': ['-volume', '-issue_number'],
            },
        ),
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=200)),
                ('role', models.CharField(choices=[('editor_in_chief', 'Editor-in-Chief'), ('associate_editor', 'Associate Editor'), ('managing_editor', 'Managing Editor'), ('section_editor', 'Section Editor'), ('editorial_board', 'Editorial Board Member'), ('reviewer', 'Reviewer'), ('advisory_board', 'Advisory Board Member')], max_length=30)),
                ('title', models.CharField(blank=True, help_text='Academic title (e.g., Dr., Prof.)', max_length=100)),
                ('affiliation', models.CharField(blank=True, help_text='Institution affiliation', max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('expertise', models.TextField(blank=True, help_text='Areas of expertise')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='journals/editorial_board/')),
                ('orcid', models.CharField(blank=True, help_text='ORCID ID', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_board', to='publications.journal')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_factor', models.DecimalField(decimal_places=3, default=0.0, help_text='Journal Impact Factor', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('cite_score', models.DecimalField(decimal_places=3, default=0.0, help_text='CiteScore metric', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('h_index', models.PositiveIntegerField(default=0, help_text='H-index')),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Acceptance rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('average_review_time', models.PositiveIntegerField(default=0, help_text='Average review time in days')),
                ('total_articles', models.PositiveIntegerField(default=0, help_text='Total published articles')),
                ('total_issues', models.PositiveIntegerField(default=0, help_text='Total published issues')),
                ('total_citations', models.PositiveIntegerField(default=0, help_text='Total citations')),
                ('total_reads', models.PositiveIntegerField(default=0, help_text='Total article reads')),
                ('recommendations', models.PositiveIntegerField(default=0, help_text='Number of recommendations')),
                ('social_media_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Social media engagement score', max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='publications.journal')),
            ],
        ),
        migrations.CreateModel(
            name='IssueArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Article order in issue')),
                ('section', models.CharField(blank=True, help_text='Section (e.g., Research, Review, Editorial)', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='publications.issue')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_appearances', to='publications.publication')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('issue', 'publication')},
            },
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['institution', '-created_at'], name='publication_institu_da7812_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['issn'], name='publication_issn_ec7f47_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['journal', '-publication_date'], name='publication_journal_a37af2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('journal', 'volume', 'issue_number')},
        ),
        migrations.AlterUniqueTogether(
            name='editorialboardmember',
            unique_together={('journal', 'email')},
        ),
    ]
