# Generated by Django 5.2.8 on 2025-12-31 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_journal_issue_editorialboardmember_journalstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Topic name (e.g., 'Computer Science')", max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this topic')),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji for UI', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this topic is active')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='publication_slug_bc3d54_idx'), models.Index(fields=['is_active', 'order'], name='publication_is_acti_494d11_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Branch name (e.g., 'Machine Learning')", max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this topic branch')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this branch is active')),
                ('order', models.IntegerField(default=0, help_text='Display order within topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='publications.topic')),
            ],
            options={
                'verbose_name_plural': 'Topic Branches',
                'ordering': ['topic', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='topic_branch',
            field=models.ForeignKey(blank=True, help_text='Topic branch this publication belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publications.topicbranch'),
        ),
        migrations.AddIndex(
            model_name='topicbranch',
            index=models.Index(fields=['topic', 'slug'], name='publication_topic_i_37600d_idx'),
        ),
        migrations.AddIndex(
            model_name='topicbranch',
            index=models.Index(fields=['topic', 'is_active', 'order'], name='publication_topic_i_7c8baf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicbranch',
            unique_together={('topic', 'slug')},
        ),
    ]
