# Generated by Django 5.2.8 on 2025-12-31 05:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_topic_topicbranch_publication_topic_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicbranch',
            options={'ordering': ['topic', 'level', 'order', 'name'], 'verbose_name_plural': 'Topic Branches'},
        ),
        migrations.RemoveIndex(
            model_name='topicbranch',
            name='publication_topic_i_37600d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='topicbranch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='topicbranch',
            name='level',
            field=models.IntegerField(default=1, help_text='Hierarchy level (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='topicbranch',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent branch for nested hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='publications.topicbranch'),
        ),
        migrations.AlterField(
            model_name='topicbranch',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within parent'),
        ),
        migrations.AlterUniqueTogether(
            name='topicbranch',
            unique_together={('topic', 'parent', 'slug')},
        ),
        migrations.AddIndex(
            model_name='topicbranch',
            index=models.Index(fields=['topic', 'parent', 'level'], name='publication_topic_i_c8cc73_idx'),
        ),
    ]
