# Generated by Django 5.2.8 on 2026-01-22 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_add_journal_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='journal_name',
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(blank=True, help_text='Journal this publication belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_publications', to='publications.journal'),
        ),
    ]
