# Generated by Django 5.2.8 on 2026-01-22 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_remove_publication_journal_name_publication_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(help_text='Journal this publication belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='journal_publications', to='publications.journal'),
        ),
    ]
